### PR TITLE
Add Job Cards to provide useful information for each supported job type.

### LINKED ISSUE #122: Add documentation for data formats
Would be nice to add information about the file/folder structure the different models expect. For example:
- specifying that multiple files should be zipped together
- specifying that segmentation and tracking take in single-channel 2D data
- specifying that multiplex takes in multichannel 2D data, with nuclear channel first and membrane channel second
- specifying that multiplex only accepts multichannel tifs with channels last, which is not the typical image format

### LINKED ISSUE #138: Display information about specific models on predict page
We should add information about what each model is, and the data it expects, somewhere on the predict page of deepcell.org so people know what they're selecting from. We should also consider changing the default to be multiplex, or not having a default at all, so that users will need to select a given model.

### PR DESCRIPTION
**Pull request by willgraf**
Display an example image and a brief description of the inputs for each job type.

This is currently hardcoded in `src/Predict/jobData.js` and will need to be updated for future job types until this information is provided by the backend API. This could eventually be brought into the `/api/jobtypes` route.

This PR also breaks the `Predict` component into several smaller components:

- `ModelDropdown`
- `JobCard`
- `ScaleForm`
- `FileUpload` was moved into the same folder for consistency.

---

Fixes #138
Fixes #122

### CODE REVIEW

**Comment by ngreenwald** [comment]
image

This looks awesome! Couple suggestions:

1. Change "Download" to "Download example image" or something like that
2. Change capitalization in Upload Here to Begin... so that only first word is capitalized
3. Change "Drag and Drop" to "Drag and drop"
4. Change "Job Type" to "Model" or something less technical feeling
5. Is it possible to display the Mesmer example image as a 2-color image?
6. Maybe changing the title to be something like "Generate model predictions"

**Comment by willgraf** [comment]
@ngreenwald Great suggestions! I've incorporated them all except 2 and 4, and the changes are live.

2. I've left the capitalized title because the other labels are also capitalized ("Rescale Automatically").

4. I've not changed it to "Job Type" because I did not like the look of just "Model".

**Comment by ngreenwald** [comment]
Okay awesome! Can you change the dropdown to Mesmer? Also, could we add a link somewhere in the FAQ to intro-to-deepcell? Maybe the "where can I get help" section?

"For an overview of the DeepCell ecocystem, please see our [introductory documentation](https://github.com/vanvalenlab/intro-to-deepcell)

**Comment by willgraf** [comment]
Good idea with the FAQ.

The dropdown value will be changed on the deployment, the job types are injected as environment variables, so they cannot be changed in this PR.

**Pull request merged**
