### PR TITLE
Replace `ScaleForm` with new `ResolutionDropdown`.

### LINKED ISSUE #165: Add scale functionality to frontend
We previously had rescaling incorporated into the frontend as part of the scale-detection module. The user had a checkbox for "rescale automatically" or "manually rescale." If the manual option was selected, then a textbox appeared that allowed the user to enter a scale factor. 

This UI was a bit confusing. It wasn't clear what automatic scale detection was, or what the units of the manual rescaling were, whether it was necessary or not, etc. 

However, given that people will be providing data outside of the expected scale range, having this functionality in place on the website would be quite useful. In particular, I think having a multiplicative factor makes the most sense. We can tell users that the model expects data of xx resolution, and if they would like to supply data of a smaller or larger resolution, they can indicate the requested scale factor to align their data with the expectations of the model.

### PR DESCRIPTION
**Pull request by willgraf**
As discussed in #165, the `ScaleForm` is a bit too unintuitive for users. It's not clear what the correct "scale" should be. This PR replaces the `ScaleForm` with a manual dropdown with common microns-per-pixel values (and the zoom level used with them). This way, the user can select if their data is 40x or 10x instead of trying to guess at the correct scale.

I think there is still room for a manual input form for image mpp, but for now, I think that the ballpark resize values will be helpful and intuitive.

Fixes #165

### CODE REVIEW

**Comment by willgraf** [comment]
I've deployed this on [deepcell.org](deepcell.org/predict) and tested with a few example files and resolution inputs.

Viewing the backend logs, I can see that the consumer is reading the scale properly and resizing the image as expected.

**Review by ngreenwald — CHANGES_REQUESTED** [review]
Looks good. I think we should remove the "Resolution" section from the model cards description now that the user has the ability to specify the input resolution. It probably makes sense to keep that info in the intro-to-deepcell docs, but having it on the front page will lead to confusion if it makes people think they can only select 20X for Mesmer.

**Comment by willgraf** [comment]
That makes sense to me. Now the content lines up a bit better on the bottom too!

I've redeployed it on the site. LMK if you see anything.

**Review by ngreenwald — APPROVED** [review]
Awesome

**Pull request merged**
